# Generated by Django 4.0 on 2021-12-19 03:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=1000)),
                ('author_grade', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField()),
                ('recommended_articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='articles.article')),
            ],
        ),
    ]
