# Generated by Django 4.0 on 2021-12-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_grade',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author'),
        ),
    ]
