# Generated by Django 4.0 on 2021-12-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=10000)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
