# Generated by Django 4.0 on 2021-12-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name',)},
        ),
    ]
